Supports 1.13.2
Pravian/Aero pull request #14
Opened 2019-01-28 14:02 UTC by Focusvity

2019-01-28 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Pravian/Aero?pullRequest=14) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Pravian/Aero?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Pravian/Aero?pullRequest=14) it.</sub>

2019-01-28 14:32 UTC, JeromSar requested changes
There are truly only minor edits here and there. Most of it seems in good order.

Could you please:
1. Use Google's formatting guidelines? A IntelliJ plugin which does this automatically is: https://plugins.jetbrains.com/plugin/8527-google-java-format
2. Avoid double paragraph tags (`<p>`) in the javadocs?
3. Ensure the class member order is consistent (e.g. static methods after instance methods).

2019-01-28 14:32 UTC, JeromSar commented on src/main/java/net/pravian/aero/util/Materials.java
> +        MATERIALS.add(Material.LEGACY_SAPLING.toString());
Considering Bukkit's `Material` class has changed a bit. Would you please switch to the new items values (i.e. avoid legacy)?

2019-01-28 14:36 UTC, Focusvity commented on src/main/java/net/pravian/aero/util/Materials.java
> +        MATERIALS.add(Material.LEGACY_SAPLING.toString());
Would you prefer if I have 2 sets? One for new items value and one for legacy?

2019-01-28 14:40 UTC, JeromSar commented on src/main/java/net/pravian/aero/util/Materials.java
> +        MATERIALS.add(Material.LEGACY_SAPLING.toString());
I don't think we'll need the legacy items. If I'm not mistaken, the legacy items are just here for backward compatibility for some functionality.

2019-01-31 01:15 UTC, Focusvity commented
@JeromSar, is there any other changes needed?

2019-02-24 10:45 UTC, Focusvity commented
Hey @JeromSar,
Is there anything you need me to change?

2020-11-17 11:30 UTC, JeromSar commented
We're up to date to 1.15.2 now. :)

2020-11-17 11:30 UTC, closed without merging